CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(50) NOT NULL UNIQUE check (email LIKE '%_@_%_.__%'),
    login    varchar(50) NOT NULL UNIQUE,
    name     varchar(50) NOT NULL,
    birthday date        NOT NULL check (birthday <= now())
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id    INTEGER NOT NULL,
    friend_id  INTEGER NOT NULL,
    friendStorage varchar(50) DEFAULT 'неподтверждённая',
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50) NOT NULL,
    description  varchar(50) NOT NULL,
    release_date date        NOT NULL check (release_date >= '1895-12-28'),
    duration     integer     NOT NULL check (duration > 0),
    mpa_id       INTEGER
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INTEGER NOT NULL,
    film_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL
);